arrowParens: 'avoid'
bracketSpacing: true
embeddedLanguageFormatting: 'auto'
htmlWhitespaceSensitivity: 'ignore'
insertPragma: false
jsxBracketSameLine: false
jsxSingleQuote: false
printWidth: 80
proseWrap: 'always'
quoteProps: 'as-needed'
requirePragma: false
semi: false
singleQuote: true
tabWidth: 2
trailingComma: 'es5'
useTabs: false
vueIndentScriptAndStyle: true
